// Ship cosmetic definitions. Pure visual — no gameplay advantage.
export const SHIP_SKINS = [
  {
    id: "default",
    name: "Cyan Pulse",
    description: "Standard issue energy ship. Reliable and bright.",
    color: "#00F5FF",
    core: "#ffffff",
    trail: "#00F5FF",
    glow: "#00F5FF",
    price: 0,
  },
  {
    id: "void",
    name: "Void Runner",
    description: "A deep-purple hull tuned for the void between waves.",
    color: "#8B5CF6",
    core: "#E9D5FF",
    trail: "#8B5CF6",
    glow: "#8B5CF6",
    price: 150,
  },
  {
    id: "solar",
    name: "Solar Flare",
    description: "Golden plating that burns bright against the dark.",
    color: "#FFD166",
    core: "#FFF7D6",
    trail: "#FFD166",
    glow: "#FFD166",
    price: 300,
  },
  {
    id: "crimson",
    name: "Crimson Phantom",
    description: "A dangerous red silhouette favored by veteran pilots.",
    color: "#FF3B5C",
    core: "#FFD7DD",
    trail: "#FF3B5C",
    glow: "#FF3B5C",
    price: 500,
  },
  {
    id: "arctic",
    name: "Arctic Nova",
    description: "Ice-blue radiance that freezes the moment.",
    color: "#7DD3FC",
    core: "#F0FDFF",
    trail: "#7DD3FC",
    glow: "#7DD3FC",
    price: 750,
  },
  {
    id: "quantum",
    name: "Quantum Ghost",
    description: "A white-violet phantom phase-shifted between states.",
    color: "#F8FAFC",
    core: "#C4B5FD",
    trail: "#C4B5FD",
    glow: "#A78BFA",
    price: 1200,
  },
  {
    id: "phoenix",
    name: "Phoenix Prime",
    description: "Premium. Molten orange-gold hull forged for elite pilots.",
    color: "#FF8A3D",
    core: "#FFE9C7",
    trail: "#FF8A3D",
    glow: "#FF6B1A",
    currency: "credits",
    creditPrice: 60,
  },
  {
    id: "aurora",
    name: "Aurora Veil",
    description: "Premium. Shifting green-teal aurora across the hull.",
    color: "#34D399",
    core: "#D1FAE5",
    trail: "#34D399",
    glow: "#10B981",
    currency: "credits",
    creditPrice: 100,
  },
  {
    id: "celestial",
    name: "Celestial Crown",
    description: "Premium. A legendary white-violet phantom for the chosen few.",
    color: "#F8FAFC",
    core: "#C4B5FD",
    trail: "#A78BFA",
    glow: "#8B5CF6",
    currency: "credits",
    creditPrice: 180,
  },
  {
    id: "phantom",
    name: "Phantom Prototype",
    description: "Story reward. The experimental PHANTOM hull — your first ship.",
    color: "#22D3EE",
    core: "#E0F7FF",
    trail: "#22D3EE",
    glow: "#22D3EE",
    currency: "story",
    unlockChapter: 1,
  },
  {
    id: "signal_hunter",
    name: "Signal Hunter",
    description: "Story reward. Tuned to trace signals through dead space.",
    color: "#A78BFA",
    core: "#F5F3FF",
    trail: "#A78BFA",
    glow: "#8B5CF6",
    currency: "story",
    unlockChapter: 3,
  },
  {
    id: "null_hunter",
    name: "Null Hunter",
    description: "Story reward. A dark hull forged to pierce the NULL defense ring.",
    color: "#FF2E93",
    core: "#FFD7E6",
    trail: "#FF2E93",
    glow: "#FF2E93",
    currency: "story",
    unlockChapter: 5,
  },
  {
    id: "legendary_phantom",
    name: "Legendary Phantom",
    description: "Story reward. The PHANTOM reborn — a legendary hull for the pilot who ended the signal.",
    color: "#F8FAFC",
    core: "#C4B5FD",
    trail: "#A78BFA",
    glow: "#8B5CF6",
    currency: "story",
    unlockChapter: 6,
  },
  {
    id: "combo_spectre",
    name: "Combo Spectre",
    description: "Achievement reward. Unlocked by reaching a x8 near-miss combo.",
    color: "#FF2E93",
    core: "#FFB3D1",
    trail: "#FF2E93",
    glow: "#FF2E93",
    currency: "achievement",
    unlockAchievement: "combo_master",
  },
  {
    id: "endurance_wraith",
    name: "Endurance Wraith",
    description: "Achievement reward. Unlocked by surviving 120 seconds in a single run.",
    color: "#34D399",
    core: "#D1FAE5",
    trail: "#34D399",
    glow: "#10B981",
    currency: "achievement",
    unlockAchievement: "marathon",
  },
];

export const SKIN_MAP = Object.fromEntries(SHIP_SKINS.map((s) => [s.id, s]));

export function getSkin(id) {
  return SKIN_MAP[id] || SHIP_SKINS[0];
}