import UserNotifications

// AUTO-GENERATED by AppNative — Notification Service Extension.
// Downloads the push payload's "image_url" and attaches it so the image shows
// on the notification banner. Do not edit by hand.

class NotificationService: UNNotificationServiceExtension {
    private var contentHandler: ((UNNotificationContent) -> Void)?
    private var bestAttempt: UNMutableNotificationContent?

    override func didReceive(_ request: UNNotificationRequest, withContentHandler contentHandler: @escaping (UNNotificationContent) -> Void) {
        self.contentHandler = contentHandler
        let mutable = request.content.mutableCopy() as? UNMutableNotificationContent
        self.bestAttempt = mutable

        guard let content = mutable else { contentHandler(request.content); return }

        let raw = (content.userInfo["image_url"] as? String) ?? ""
        guard !raw.isEmpty, let url = URL(string: raw) else { contentHandler(content); return }

        URLSession.shared.downloadTask(with: url) { tmpURL, response, _ in
            defer { contentHandler(content) }
            guard let tmpURL = tmpURL else { return }
            // The attachment must keep a real image extension or iOS silently drops it.
            var ext = url.pathExtension.lowercased()
            if !["png", "jpg", "jpeg", "gif", "heic"].contains(ext) {
                let mime = (response as? HTTPURLResponse)?.mimeType ?? ""
                if mime.contains("png") { ext = "png" }
                else if mime.contains("gif") { ext = "gif" }
                else { ext = "jpg" }
            }
            let dest = tmpURL.deletingLastPathComponent().appendingPathComponent(UUID().uuidString + "." + ext)
            do {
                try FileManager.default.moveItem(at: tmpURL, to: dest)
                let attachment = try UNNotificationAttachment(identifier: "appnative_image", url: dest, options: nil)
                content.attachments = [attachment]
            } catch {
                print("[AppNative] notification image attach failed: \(error.localizedDescription)")
            }
        }.resume()
    }

    // Apple gives the extension ~30s. Always deliver something.
    override func serviceExtensionTimeWillExpire() {
        if let content = bestAttempt { contentHandler?(content) }
    }
}
