import UIKit
import WebKit
import CoreImage

// AUTO-GENERATED by AppNative — adaptive safe-area theming.
// This file EXTENDS WebViewController without modifying it. Do not edit by hand.

private var anThemeTimerKey: UInt8 = 0
private var anThemeLastKey: UInt8 = 0
private var anOrigTopKey: UInt8 = 0
private var anFullTopKey: UInt8 = 0

extension WebViewController {
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        anStartAdaptiveTheme()
        anInstallUXBridge()
    }

    private var anThemeTimer: Timer? {
        get { objc_getAssociatedObject(self, &anThemeTimerKey) as? Timer }
        set { objc_setAssociatedObject(self, &anThemeTimerKey, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) }
    }

    private var anLastCSS: String? {
        get { objc_getAssociatedObject(self, &anThemeLastKey) as? String }
        set { objc_setAssociatedObject(self, &anThemeLastKey, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) }
    }

    func anStartAdaptiveTheme() {
        guard anThemeTimer == nil else { return }
        anSampleThemeColor()
        let t = Timer.scheduledTimer(withTimeInterval: 0.8, repeats: true) { [weak self] _ in
            self?.anSampleThemeColor()
        }
        anThemeTimer = t
    }

    private func anSampleThemeColor() {
        // Never resolve a color while the page is being touched or is bouncing.
        // Rubber-band overscroll slides other elements under the notch, so probing
        // mid-gesture picked up whatever happened to be there and flipped the safe
        // area back and forth even though the page never actually moved.
        if let sv = webView?.scrollView, sv.isTracking || sv.isDragging || sv.isDecelerating { return }
        let js = """
        (function(){
          try {
            // Cheap gate: the full probe below forces a style+layout pass, so it must
            // only run when something could actually have changed the safe-area color
            // (navigation, light/dark toggle, rotation, foreground) — not on every
            // poll. Never while a native recording holds the audio session either.
            if (!window.AppNative) { window.AppNative = {}; }
            var AN = window.AppNative;
            if (!AN._tdInit) {
              AN._tdInit = true;
              AN._themeDirty = true;
              var mark = function(){ AN._themeDirty = true; };
              var evs = ["popstate", "hashchange", "orientationchange", "resize", "pageshow", "focus"];
              for (var q = 0; q < evs.length; q++) { window.addEventListener(evs[q], mark); }
              try { document.addEventListener("visibilitychange", mark); } catch(e) {}
              try {
                var ps = history.pushState, rs = history.replaceState;
                history.pushState = function(){ var r = ps.apply(this, arguments); mark(); return r; };
                history.replaceState = function(){ var r = rs.apply(this, arguments); mark(); return r; };
              } catch(e) {}
              try { new MutationObserver(mark).observe(document.documentElement, {attributes: true, attributeFilter: ["class", "data-theme", "style"]}); } catch(e) {}
            }
            if (AN._nativeRecording) { return "SKIP"; }
            if (!AN._themeDirty) { return "SKIP"; }
            var fb = false;
            if (window.AppNative && typeof window.AppNative.fullBleed === "boolean") { fb = window.AppNative.fullBleed; }
            else {
              var fbp = [];
              var p = location.pathname;
              for (var i = 0; i < fbp.length; i++) { if (p === fbp[i] || p.indexOf(fbp[i] + "/") === 0) { fb = true; break; } }
            }
            var c = "";
            if (window.AppNative && window.AppNative.safeAreaColor) { c = String(window.AppNative.safeAreaColor); }
            // Opaque = has a real alpha. Parse the alpha channel properly — a
            // naive ", 0)" substring test also matches "rgb(0, 0, 0)" (pure black),
            // which made every black page fall through to the theme-color meta tag.
            var opaque = function(bg) {
              if (!bg) return false;
              bg = String(bg).trim();
              if (bg === "transparent" || bg === "none") return false;
              var lb = bg.indexOf("(");
              if (lb > -1) {
                var inner = bg.slice(lb + 1, bg.indexOf(")"));
                var parts = inner.split(",").join("/").split("/").map(function(s){ return parseFloat(s); });
                if (parts.length >= 4 && !(parts[3] > 0)) return false;
                return true;
              }
              if (bg.charAt(0) === "#") { return !(bg.length === 5 && bg.slice(-1) === "0") && !(bg.length === 9 && bg.slice(-2) === "00"); }
              return true;
            };
            // Resolve the color that is actually painted at the top of the page.
            // The safe area sits directly above <body>, so the body/html computed
            // background is the correct match whenever it is opaque — and unlike a
            // snapshot it can never fail. If both are transparent (page painted by
            // an inner container, gradient or image) walk up from the elements at
            // the very top of the viewport, and only then fall back to sampling
            // the rendered pixels.
            // First color found inside a background-image value (gradients).
            // Written without regex on purpose: backslashes would be parsed as
            // Swift string escapes inside the generated multiline literal.
            var firstColor = function(str) {
              var s = String(str || "");
              var i = s.indexOf("rgb");
              if (i > -1) { var j = s.indexOf(")", i); if (j > -1) return s.slice(i, j + 1); }
              i = s.indexOf("#");
              if (i > -1) {
                var k = i + 1;
                while (k < s.length && "0123456789abcdefABCDEF".indexOf(s.charAt(k)) > -1) { k++; }
                return s.slice(i, k);
              }
              return "";
            };
            // Paintable background of one element: its background-color when
            // opaque, otherwise the first color stop of its gradient/image.
            var bgOf = function(el) {
              var st = getComputedStyle(el);
              if (opaque(st.backgroundColor)) return st.backgroundColor;
              var bi = st.backgroundImage;
              if (bi && bi !== "none") { var c = firstColor(bi); if (opaque(c)) return c; }
              return "";
            };
            var walkUp = function(el) {
              while (el) {
                var bg = bgOf(el);
                if (bg) return bg;
                el = el.parentElement;
              }
              return "";
            };
            // Like walkUp, but ignores small elements. Whatever happens to be
            // scrolled under the notch (a card, a banner, a colored section) must
            // NOT set the safe-area color — only a page-level container that
            // spans most of the viewport counts, so the color stays stable while
            // the user scrolls.
            var walkUpPage = function(el) {
              var minH = window.innerHeight * 0.6;
              while (el) {
                if (el === document.body || el === document.documentElement) return bgOf(el);
                var r = el.getBoundingClientRect();
                if (r.height >= minH && r.width >= window.innerWidth * 0.9) {
                  var bg = bgOf(el);
                  if (bg) return bg;
                }
                el = el.parentElement;
              }
              return "";
            };
            // A pinned mobile header sits directly under the safe area, so when one
            // exists IT is what the safe area must match — matching the page
            // background instead leaves a visible seam across the top of the header.
            // Only bars that are actually stuck to the top of the viewport and span
            // its full width count; a scrolled-away header is ignored.
            var findHeader = function() {
              var cands = [];
              try { cands = [].slice.call(document.querySelectorAll("header, [data-mobile-header]")); } catch(e) {}
              try {
                var seeds = [document.elementFromPoint(Math.floor(window.innerWidth / 2), 2), document.elementFromPoint(4, 2)];
                for (var k = 0; k < seeds.length; k++) {
                  var e2 = seeds[k];
                  while (e2 && e2 !== document.body) { cands.push(e2); e2 = e2.parentElement; }
                }
              } catch(e) {}
              for (var i = 0; i < cands.length; i++) {
                var el = cands[i];
                if (!el || !el.getBoundingClientRect) continue;
                var st = getComputedStyle(el);
                if (st.display === "none" || st.visibility === "hidden" || parseFloat(st.opacity) === 0) continue;
                var pinned = st.position === "fixed" || st.position === "sticky";
                if (!pinned && el.tagName !== "HEADER") continue;
                var r = el.getBoundingClientRect();
                if (r.top > 2 || r.bottom <= 2) continue;
                if (r.width < window.innerWidth * 0.9) continue;
                if (r.height < 8 || r.height > window.innerHeight * 0.4) continue;
                var bg = walkUp(el);
                if (bg) return bg;
              }
              return "";
            };
            // Detects the page's current light/dark mode.
            var anIsDark = function() {
              try {
                var d = document.documentElement;
                return (" " + (d.className || "") + " ").indexOf(" dark ") > -1 ||
                       (d.getAttribute("data-theme") || "").indexOf("dark") > -1 ||
                       (getComputedStyle(d).colorScheme || "").indexOf("dark") > -1;
              } catch(e) { return false; }
            };
            // Explicit override chosen in AppNative — beats all page detection.
            if (!opaque(c)) {
              var ov = anIsDark() ? "" : "";
              if (opaque(ov)) { c = ov; }
            }
            if (!opaque(c)) { c = findHeader(); }
            // No header — match the page's own background.
            if (!opaque(c)) {
              // Probe the elements ACTUALLY painted at the top of the viewport
              // first. body/html are last-resort only: an app whose page colors
              // come from inner containers (not a .dark class on the document)
              // leaves body opaque-white on every page, so probing it first
              // returned white for dark pages too.
              var probes = [];
              try { probes.push(document.elementFromPoint(Math.floor(window.innerWidth / 2), 4)); } catch(e) {}
              try { probes.push(document.elementFromPoint(4, 4)); } catch(e) {}
              probes.push(document.body, document.documentElement);
              for (var j = 0; j < probes.length; j++) {
                var got = probes[j] ? walkUpPage(probes[j]) : "";
                if (got) { c = got; break; }
              }
            }
            // Still nothing (gradient/image background) — use the --background token
            // read from the app's own stylesheet in GitHub at build time.
            if (!opaque(c)) {
              var isDark = false;
              try {
                var d = document.documentElement;
                isDark = (" " + (d.className || "") + " ").indexOf(" dark ") > -1 ||
                         (d.getAttribute("data-theme") || "").indexOf("dark") > -1 ||
                         (getComputedStyle(d).colorScheme || "").indexOf("dark") > -1;
              } catch(e) {}
              var baked = isDark ? "" : "#09090b";
              if (opaque(baked)) { c = baked; }
            }
            if (!opaque(c)) { c = "SNAP"; }
            // Path is part of the payload so the native cache key changes on
            // navigation — a pixel-sampled page re-samples when the route changes
            // but NOT on every poll while the user scrolls. A theme signature is
            // folded in alongside it so toggling light/dark ALSO busts the cache
            // (otherwise switching back to an already-sampled theme produced an
            // identical payload and the safe area kept the other theme's color).
            var sig = "";
            try {
              var de = document.documentElement;
              sig = (de.className || "") + "|" + (de.getAttribute("data-theme") || "") +
                    "|" + getComputedStyle(de).backgroundColor +
                    "|" + getComputedStyle(document.body).backgroundColor +
                    "|" + getComputedStyle(de).colorScheme;
            } catch(e) {}
            return (fb ? "1|" : "0|") + location.pathname + "@" + sig + "|" + (c || "");
          } catch(e) { return "0||"; }
        })()
        """
        webView?.evaluateJavaScript(js) { [weak self] result, _ in
            guard let self = self, let raw = result as? String, !raw.isEmpty else { return }
            // Nothing changed since the last resolved color (or a take is recording).
            if raw == "SKIP" { return }
            // Payload is "fullBleed|<cache key>|color". The cache key itself contains
            // "|" separators, so the color MUST be read from the LAST field — splitting
            // with maxSplits: 2 handed back part of the cache key instead of the color
            // and every color update was silently dropped.
            let parts = raw.split(separator: "|", omittingEmptySubsequences: false)
            guard parts.count >= 3 else { return }
            let fullBleed = parts[0] == "1"
            let css = String(parts[parts.count - 1])
            // Resolved something usable — stop probing until the page changes again.
            // A failed resolve deliberately leaves the flag set so the next tick retries.
            if css == "SNAP" || UIColor.anFromCSS(css) != nil { self.anClearThemeDirty() }
            // Cache on the ROUTE + THEME key only (everything except the color).
            // The color itself must NOT bust the cache: a page resolves its safe-area
            // color exactly ONCE, and only a navigation or a light/dark switch can
            // change it again.
            let key = parts.dropLast().joined(separator: "|")
            guard key != self.anLastCSS else { return }
            self.anLastCSS = key
            // No CSS color anywhere (page painted with a background image or
            // gradient) — read the actual rendered pixels instead.
            if css == "SNAP" {
                DispatchQueue.main.async { self.anSetFullBleed(fullBleed) }
                self.anSampleRenderedPixel()
                return
            }
            let color = UIColor.anFromCSS(css)
            DispatchQueue.main.async {
                self.anSetFullBleed(fullBleed)
                guard let color = color else { return }
                self.anApplyThemeColor(color)
            }
        }
    }

    // Reads the page's ACTUAL rendered pixels — the only source that always
    // matches what the user sees, whatever the page uses to paint itself.
    // Sampled once per route (the JS payload is cached by path), then re-checked
    // twice in case the first snapshot landed before the page finished painting.
    private func anSampleRenderedPixel(attempt: Int = 0) {
        guard let wv = webView, wv.bounds.width > 20, wv.bounds.height > 20 else { return }
        let cfg = WKSnapshotConfiguration()
        // A thin FULL-WIDTH strip at the VERY TOP of the page: the safe area sits
        // directly above these pixels, so matching them is by definition seamless.
        // (A tall left-gutter strip ran alongside glowing card borders further down
        // the page and picked up their tint — "close but off" safe-area colors.)
        cfg.rect = CGRect(x: 0, y: 0, width: wv.bounds.width, height: 8)
        cfg.afterScreenUpdates = true
        wv.takeSnapshot(with: cfg) { [weak self] image, _ in
            guard let self = self else { return }
            // Only paint when the snapshot actually produced a color. A failed
            // snapshot must NOT fall back to the configured background color —
            // that is what left the safe area black on light-mode pages. Keeping
            // the current color and retrying below is always closer to correct.
            if let color = image?.anDominantColor {
                DispatchQueue.main.async { self.anApplyThemeColor(color) }
            }
            if attempt < 4 {
                DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) {
                    self.anSampleRenderedPixel(attempt: attempt + 1)
                }
            }
        }
    }

    private func anClearThemeDirty() {
        DispatchQueue.main.async { [weak self] in
            self?.webView?.evaluateJavaScript("try { window.AppNative._themeDirty = false; } catch(e){}", completionHandler: nil)
        }
    }

    private func anApplyThemeColor(_ color: UIColor) {
        let block = {
                self.view.backgroundColor = color
                self.webView?.backgroundColor = color
                self.webView?.scrollView.backgroundColor = color
                // Status bar text follows the same rules: dark text on light
                // backgrounds, light text on dark backgrounds.
                var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 0
                color.getRed(&r, green: &g, blue: &b, alpha: &a)
                let lum = 0.299 * r + 0.587 * g + 0.114 * b
                anStatusBarStyleOverride = lum > 0.6 ? .darkContent : .lightContent
                self.setNeedsStatusBarAppearanceUpdate()
        }
        if Thread.isMainThread { block() } else { DispatchQueue.main.async(execute: block) }
    }

    // Swaps the web view's top constraint between the safe-area guide and the raw
    // screen top, so configured pages (e.g. a full-screen video login) render
    // edge-to-edge under the notch while every other page keeps its safe area.
    private func anSetFullBleed(_ on: Bool) {
        guard let wv = webView else { return }
        var orig = objc_getAssociatedObject(self, &anOrigTopKey) as? NSLayoutConstraint
        if orig == nil {
            orig = view.constraints.first(where: { $0.firstItem === wv && $0.firstAttribute == .top })
            objc_setAssociatedObject(self, &anOrigTopKey, orig, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
        guard let origC = orig else { return }
        var full = objc_getAssociatedObject(self, &anFullTopKey) as? NSLayoutConstraint
        if full == nil {
            full = wv.topAnchor.constraint(equalTo: view.topAnchor)
            objc_setAssociatedObject(self, &anFullTopKey, full, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        }
        guard let fullC = full else { return }
        if on && origC.isActive {
            origC.isActive = false
            fullC.isActive = true
            UIView.animate(withDuration: 0.2) { self.view.layoutIfNeeded() }
        } else if !on && fullC.isActive {
            fullC.isActive = false
            origC.isActive = true
            UIView.animate(withDuration: 0.2) { self.view.layoutIfNeeded() }
        }
    }
}

extension UIImage {
    // DOMINANT (most common) color of the image — used to derive a safe-area color
    // from pages whose background is an image, gradient or video rather than a CSS
    // color. A plain average blends card-border glows, shadows and text that touch
    // the sampled strip into the result, producing a "close but off" tint; the mode
    // ignores those minority pixels and returns the actual background color.
    var anDominantColor: UIColor? {
        guard let cg = cgImage else { return nil }
        // Downscale into a small sRGB bitmap so histogramming stays cheap and the
        // pixel values match what the user actually sees.
        let w = min(cg.width, 160), h = min(cg.height, 160)
        guard w > 0, h > 0, let space = CGColorSpace(name: CGColorSpace.sRGB) else { return nil }
        var pixels = [UInt8](repeating: 0, count: w * h * 4)
        guard let ctx = CGContext(data: &pixels, width: w, height: h, bitsPerComponent: 8, bytesPerRow: w * 4, space: space, bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else { return nil }
        ctx.interpolationQuality = .none
        ctx.draw(cg, in: CGRect(x: 0, y: 0, width: w, height: h))
        // Quantize each channel to 16 levels, count buckets, and keep per-bucket
        // channel sums so the winner can be returned at full precision.
        var counts = [Int: (n: Int, r: Int, g: Int, b: Int)]()
        var best = -1, bestN = 0
        var i = 0
        while i < pixels.count {
            let r = Int(pixels[i]), g = Int(pixels[i + 1]), b = Int(pixels[i + 2])
            let key = ((r >> 4) << 8) | ((g >> 4) << 4) | (b >> 4)
            var e = counts[key] ?? (0, 0, 0, 0)
            e = (e.n + 1, e.r + r, e.g + g, e.b + b)
            counts[key] = e
            if e.n > bestN { bestN = e.n; best = key }
            i += 4
        }
        guard best >= 0, let e = counts[best], e.n > 0 else { return nil }
        return UIColor(red: CGFloat(e.r) / CGFloat(e.n) / 255, green: CGFloat(e.g) / CGFloat(e.n) / 255, blue: CGFloat(e.b) / CGFloat(e.n) / 255, alpha: 1)
    }
}

extension UIColor {
    // Parses "#rgb", "#rrggbb", "rgb(r, g, b)" and "rgba(r, g, b, a)" CSS colors.
    static func anFromCSS(_ css: String) -> UIColor? {
        let s = css.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if s.hasPrefix("#") {
            var hex = String(s.dropFirst())
            if hex.count == 3 { var e = ""; for ch in hex { e.append(ch); e.append(ch) }; hex = e }
            guard hex.count >= 6, let int = UInt64(hex.prefix(6), radix: 16) else { return nil }
            return UIColor(red: CGFloat((int >> 16) & 0xFF) / 255, green: CGFloat((int >> 8) & 0xFF) / 255, blue: CGFloat(int & 0xFF) / 255, alpha: 1)
        }
        if s.hasPrefix("rgb") {
            let nums = s.components(separatedBy: CharacterSet(charactersIn: "(),")).compactMap { Double($0.trimmingCharacters(in: .whitespaces)) }
            guard nums.count >= 3 else { return nil }
            if nums.count >= 4 && nums[3] == 0 { return nil }
            return UIColor(red: CGFloat(nums[0] / 255), green: CGFloat(nums[1] / 255), blue: CGFloat(nums[2] / 255), alpha: 1)
        }
        return nil
    }
}
