import UIKit
import WebKit
import StoreKit

// AUTO-GENERATED by AppNative — native UX bridge (haptics + App Review prompt).
// This file EXTENDS WebViewController without modifying it. Do not edit by hand.

private var anUXHandlerKey: UInt8 = 0
private var anMicObsKey: UInt8 = 0

// Screen stays awake while EITHER the web app asked for it (keepAwake(true)) OR
// the page is actively capturing from the microphone.
var anMicKeepAwake = false
var anManualKeepAwake = false
func anApplyIdleTimer() {
    UIApplication.shared.isIdleTimerDisabled = anMicKeepAwake || anManualKeepAwake
}

final class ANUXBridgeHandler: NSObject, WKScriptMessageHandler {
    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
        guard message.name == "appNativeUX",
              let body = message.body as? [String: Any],
              let action = body["action"] as? String else { return }
        switch action {
        case "haptic":
            let style = (body["style"] as? String) ?? "light"
            DispatchQueue.main.async {
                switch style {
                case "success": UINotificationFeedbackGenerator().notificationOccurred(.success)
                case "warning": UINotificationFeedbackGenerator().notificationOccurred(.warning)
                case "error": UINotificationFeedbackGenerator().notificationOccurred(.error)
                case "medium": UIImpactFeedbackGenerator(style: .medium).impactOccurred()
                case "heavy": UIImpactFeedbackGenerator(style: .heavy).impactOccurred()
                case "selection": UISelectionFeedbackGenerator().selectionChanged()
                default: UIImpactFeedbackGenerator(style: .light).impactOccurred()
                }
            }
        case "requestReview":
            DispatchQueue.main.async {
                if let scene = UIApplication.shared.connectedScenes.compactMap({ $0 as? UIWindowScene }).first(where: { $0.activationState == .foregroundActive }) {
                    SKStoreReviewController.requestReview(in: scene)
                }
            }
        case "keepAwake":
            let on = (body["on"] as? Bool) ?? true
            DispatchQueue.main.async { anManualKeepAwake = on; anApplyIdleTimer() }
        default: break
        }
    }
}

extension WebViewController {
    func anInstallUXBridge() {
        guard objc_getAssociatedObject(self, &anUXHandlerKey) == nil, let wv = webView else { return }
        let handler = ANUXBridgeHandler()
        objc_setAssociatedObject(self, &anUXHandlerKey, handler, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
        wv.configuration.userContentController.add(handler, name: "appNativeUX")
        let shim = """
        (function(){
          window.AppNative = window.AppNative || {};
          window.AppNative.keepAwake = function(on){ try { window.webkit.messageHandlers.appNativeUX.postMessage({action: "keepAwake", on: on !== false}); } catch(e){} };
          window.ShipWrap = window.ShipWrap || window.AppNative;
        })();
        """
        wv.configuration.userContentController.addUserScript(WKUserScript(source: shim, injectionTime: .atDocumentStart, forMainFrameOnly: false))
        wv.evaluateJavaScript(shim, completionHandler: nil)
    }
}
