import UIKit
import WebKit
import UserNotifications

// AUTO-GENERATED by AppNative — Rich Notifications: registers notification categories
// (action buttons) and routes taps/actions to in-app paths. Config is baked in at
// build time from the platform's Rich Notifications editor. Do not edit by hand.
enum AppRichPush {
    // (categoryId, [(actionId, title, path)])
    static let categories: [(String, [(String, String, String)])] = [

    ]
    // Categories used by custom notification layouts (Notification Content Extension).
    // Apple requires these to be registered by the app even when they have no actions.
    static let layoutCategories: [String] = []
    static let baseURL = "https://the-neonrush.base44.app"

    static func register() {
        var set = Set<UNNotificationCategory>()
        for (catId, actions) in categories {
            let acts = actions.map { UNNotificationAction(identifier: $0.0, title: $0.1, options: [.foreground]) }
            set.insert(UNNotificationCategory(identifier: catId, actions: acts, intentIdentifiers: [], options: []))
        }
        for catId in layoutCategories where !categories.contains(where: { $0.0 == catId }) {
            set.insert(UNNotificationCategory(identifier: catId, actions: [], intentIdentifiers: [], options: []))
        }
        UNUserNotificationCenter.current().setNotificationCategories(set)
    }

    static func path(forAction actionId: String) -> String? {
        for (_, actions) in categories {
            for a in actions where a.0 == actionId { return a.2 }
        }
        return nil
    }

    // Merge the push's custom data payload into a path as query params, so the web app
    // can read per-notification values (e.g. bookingId) straight off the URL. Reserved
    // keys used for delivery/rendering are skipped. Also stamps ?action=<id> so the app
    // knows which button was tapped. Returns the path with a merged query string.
    static func pathWithPayload(_ path: String, userInfo: [AnyHashable: Any], actionId: String?) -> String {
        let reserved: Set<String> = ["aps", "deep_link", "category", "sound", "mutable-content", "app_id"]
        var params: [String] = []
        for (rawKey, rawVal) in userInfo {
            guard let key = rawKey as? String, !reserved.contains(key) else { continue }
            let val: String
            if let s = rawVal as? String { val = s }
            else if let n = rawVal as? NSNumber { val = n.stringValue }
            else { continue }
            let ek = key.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? key
            let ev = val.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? val
            params.append("(ek)=(ev)")
        }
        if let a = actionId, !a.isEmpty {
            let ea = a.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed) ?? a
            params.append("action=(ea)")
        }
        if params.isEmpty { return path }
        let sep = path.contains("?") ? "&" : "?"
        return path + sep + params.joined(separator: "&")
    }
}

extension WebViewController {
    // Wired into the END of viewDidLoad at CI time (perl injection, verified in the workflow).
    func setupRichPush() {
        AppRichPush.register()
    }

    // Navigate the WebView to the action's path. Works on cold launch too — the
    // targeted load simply replaces the in-flight initial root load.
    func openRichPushPath(_ path: String) {
        guard let url = URL(string: AppRichPush.baseURL + path) else { return }
        if let wv = webView {
            wv.load(URLRequest(url: url))
        } else {
            DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { [weak self] in
                self?.webView?.load(URLRequest(url: url))
            }
        }
    }
}

extension AppDelegate {
    // Handles action-button taps AND the default notification tap (deep_link data key).
    // Safe as an extension: the generated AppDelegate does not implement didReceive.
    func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
        let userInfo = response.notification.request.content.userInfo
        var path: String? = nil
        var actionId: String? = nil
        switch response.actionIdentifier {
        case UNNotificationDefaultActionIdentifier:
            path = userInfo["deep_link"] as? String
        case UNNotificationDismissActionIdentifier:
            break
        default:
            actionId = response.actionIdentifier
            path = AppRichPush.path(forAction: response.actionIdentifier)
        }
        if let p = path, p.hasPrefix("/"), let vc = window?.rootViewController as? WebViewController {
            // Carry the push's custom data (e.g. bookingId) into the URL as query params
            // so the opened page can act on it with zero extra wiring.
            let full = AppRichPush.pathWithPayload(p, userInfo: userInfo, actionId: actionId)
            vc.openRichPushPath(full)
        }
        completionHandler()
    }
}
